Import libraries

In [5]:
import pandas as pd

Read file csv

In [46]:
df = pd.read_csv (r"C:\Users\DELL\OneDrive\Documents\DA\LearnDA\Portfolio\Graduation_grades\formatted_students_scores.csv")
df.rename(columns={'CityName': 'ThanhPho', 'Code': 'SBD'}, inplace=True)
# Move Toan NguVan NgoaiNgu before SBD
cols = df.columns.tolist()
print (cols)
new_order = ['ThanhPho', 'SBD', 'Toan', 'NguVan', 'NgoaiNgu', 'VatLi', 'HoaHoc', 'SinhHoc', 'LichSu', 'DiaLi', 'GDCD']
df = df[new_order]
df.fillna(0, inplace=True)

['ThanhPho', 'SBD', 'DiaLi', 'GDCD', 'HoaHoc', 'LichSu', 'NgoaiNgu', 'NguVan', 'SinhHoc', 'Toan', 'VatLi']

In [47]:
df

,ThanhPho,SBD,Toan,NguVan,NgoaiNgu,VatLi,HoaHoc,SinhHoc,LichSu,DiaLi,GDCD
0,Hà Nội,1000001,8.4,6.75,8.0,6.00,5.25,5.0,0.00,0.00,0.00
1,Hà Nội,1000002,8.6,8.50,7.2,0.00,0.00,0.0,7.25,6.00,8.00
2,Hà Nội,1000003,8.2,8.75,8.2,0.00,0.00,0.0,7.25,7.25,8.75
3,Hà Nội,1000004,4.8,8.50,7.4,0.00,0.00,0.0,7.00,6.00,7.50
4,Hà Nội,1000005,8.6,9.00,7.8,0.00,0.00,0.0,9.00,8.75,8.50
...,...,...,...,...,...,...,...,...,...,...,...
1061600,Hậu Giang,64007282,4.2,6.00,3.0,0.00,0.00,0.0,5.25,6.25,7.50
1061601,Hậu Giang,64007283,5.2,6.00,3.6,0.00,0.00,0.0,6.25,5.75,7.75
1061602,Hậu Giang,64007284,7.2,8.00,7.0,6.25,7.00,8.0,0.00,0.00,0.00
1061603,Hậu Giang,64007285,5.2,5.25,4.4,0.00,0.00,0.0,4.75,6.50,8.75
1061604,Hậu Giang,64007286,5.8,8.25,2.8,0.00,0.00,0.0,5.00,7.25,8.25

In [48]:
so_hoc_sinh_moi_tinh = df.groupby('ThanhPho').size().reset_index(name='SoHocSinh')
print(so_hoc_sinh_moi_tinh)

           ThanhPho  SoHocSinh
0          An Giang      20251
1   Bà Rịa-Vũng Tàu      12635
2        Bình Dương      15239
3        Bình Phước      11304
4        Bình Thuận      13133
..              ...        ...
58          Đà Nẵng      13414
59         Đăk Nông       7681
60          Đắk Lắk      20865
61         Đồng Nai      33800
62        Đồng Tháp      16464

[63 rows x 2 columns]

In [49]:
# Tách dữ liệu cho khối tự nhiên
df_tn = df[(df['GDCD'] == 0) & (df['DiaLi'] == 0) & (df['LichSu'] == 0)]

# Tách dữ liệu cho khối xã hội
df_xh = df[(df['VatLi'] == 0) & (df['HoaHoc'] == 0) & (df['SinhHoc'] == 0)]

df_tn = df_tn.drop(columns=['GDCD', 'DiaLi', 'LichSu'])
df_xh = df_xh.drop(columns=['VatLi', 'HoaHoc', 'SinhHoc'])

df_tn
# # Hiển thị kết quả
# print("Học sinh thi khối tự nhiên:")
# print(df_tn.head())

# print("\nHọc sinh thi khối xã hội:")
# print(df_xh.head())

          ThanhPho       SBD  Toan  NguVan  NgoaiNgu  VatLi  HoaHoc  SinhHoc
0           Hà Nội   1000001   8.4    6.75       8.0   6.00    5.25     5.00
8           Hà Nội   1000009   8.2    8.00       8.6   8.25    4.25     6.00
10          Hà Nội   1000011   7.2    8.50       9.0   7.75    6.75     6.25
16          Hà Nội   1000017   7.0    8.75       7.8   3.75    7.50     7.25
17          Hà Nội   1000018   8.2    6.00       9.0   7.75    6.75     6.75
...            ...       ...   ...     ...       ...    ...     ...      ...
1061589  Hậu Giang  64007271   7.8    6.50       5.2   7.50    7.00     5.75
1061590  Hậu Giang  64007272   6.8    7.25       5.8   6.25    7.25     7.00
1061592  Hậu Giang  64007274   7.0    7.50       5.0   3.00    6.25     6.00
1061599  Hậu Giang  64007281   6.4    7.25       3.8   5.75    4.50     4.25
1061602  Hậu Giang  64007284   7.2    8.00       7.0   6.25    7.00     8.00

[354726 rows x 8 columns]